name = "vite-react-template1"
main = "src/worker.js"
compatibility_date = "2026-06-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[vars]
LEADS_ALLOWED_ORIGIN = "https://dalaillama.in"

[[kv_namespaces]]
binding = "LEADS_KV"
id = "6746c37be7b54aeaa37c1e7ebeac9381"
preview_id = "4faf29f726ae49ffa6a10a7a4bd33903"
