const PUBLISHED_DATE = "July 1, 2026";
const HERO_IMAGE = "/blog/reddit-shorts-editing-workflow/shorts-editing-workflow.png";

const referenceLibrary = {
  youtubeShorts: {
    label: "YouTube Help: Get started creating YouTube Shorts",
    url: "https://support.google.com/youtube/answer/10059070",
    note: "for Shorts format, upload, and creator context",
  },
  w3cMedia: {
    label: "W3C WAI: Making Audio and Video Media Accessible",
    url: "https://www.w3.org/WAI/media/av/",
    note: "for captions, transcripts, and accessible media decisions",
  },
  googleMeet: {
    label: "Google Meet Help: Record a video meeting",
    url: "https://support.google.com/meet/answer/9308681",
    note: "for recording, captions, Drive storage, and participant consent context",
  },
  microsoftTeams: {
    label: "Microsoft Support: Start, stop, and find meeting recordings in Teams",
    url: "https://support.microsoft.com/en-US/teams/meetings/start-stop-and-find-meeting-recordings-in-microsoft-teams",
    note: "for Teams recording, transcript, OneDrive, and SharePoint details",
  },
  zoomSupport: {
    label: "Zoom Support",
    url: "https://support.zoom.com/hc/en",
    note: "for current Zoom recording and account permission documentation",
  },
  ffmpegDocs: {
    label: "FFmpeg documentation",
    url: "https://ffmpeg.org/documentation.html",
    note: "for technical video processing, scaling, encoding, and audio tooling",
  },
  secEdgar: {
    label: "SEC EDGAR full text search",
    url: "https://www.sec.gov/edgar/search/",
    note: "for checking public company filings around earnings and investor communications",
  },
  parliamentLive: {
    label: "Parliamentlive.tv",
    url: "https://www.parliamentlive.tv/",
    note: "for official parliamentary video context and archives",
  },
};

const supportingGuides = {
  "ai-video-workflow-digital-publishers": "AI Video Workflow for Digital Publishers",
  "ai-video-editing-newsrooms": "AI Video Editing for Newsrooms",
  "reddit-shorts-editing-workflow": "What Reddit Creators Actually Ask About Shorts Editing",
  "short-form-video-editor-attention-span": "Short-Form Video Editing: How to Hold Attention",
  "reel-patterns-worth-editing": "Reel Patterns Worth Editing",
  "youtube-shorts-hooks": "How to Write Better Hooks for YouTube Shorts",
};

export const sourceToShortsConfigs = [
  {
    source: "Podcast",
    slug: "turn-podcast-into-shorts",
    title: "Turn Podcast into Shorts: Clip-Worthy Episode Workflow",
    description: "A focused workflow for turning podcast episodes into captioned Shorts without flattening the host, guest, or argument.",
    primaryKeyword: "turn podcast into shorts",
    audience: "podcast teams, founders, and creator-led brands",
    searchIntent: "repurpose a long episode into speaker-led Shorts",
    distinction: "A podcast Short has to carry a full idea without the listener hearing the warm-up, sponsor read, or private host context. The edit should feel like a sharp excerpt, not a random sentence pulled from a long conversation.",
    bestMoment: "A guest makes a clear claim, tells a compact story, challenges a common belief, or gives a practical answer the audience can use immediately.",
    avoid: "Episode summaries, inside jokes, cold opens with no context, and clips where the payoff depends on three minutes of previous conversation.",
    reviewOwner: "producer or host",
    workflow: [
      "Create a transcript with speaker labels, then mark claims, stories, surprising numbers, and clean question-answer pairs.",
      "Choose one idea per Short and write a hook from the listener's problem, not from the episode title.",
      "Trim the host setup aggressively while keeping enough context for the guest answer to make sense.",
      "Use captions to clarify names, jargon, and quiet phrases that would be missed on mobile.",
      "Export a vertical cut with the active speaker centered and any show branding kept small.",
    ],
    signals: [
      "The clip has one complete thought that lands in under 60 seconds.",
      "The first line creates tension, curiosity, or practical value without clickbait.",
      "The guest's voice carries authority, emotion, or a strong point of view.",
    ],
    guardrails: [
      "Do not crop out reactions that make the answer feel human.",
      "Avoid cutting mid-thought just because the sentence sounds quotable.",
      "Check guest approvals when the episode agreement requires it.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-interview-into-shorts", "turn-youtube-video-into-shorts", "reddit-shorts-editing-workflow"],
    funnel: "MOFU",
    businessIntent: "podcast repurposing order",
  },
  {
    source: "Interview",
    slug: "turn-interview-into-shorts",
    title: "Turn Interview into Shorts: Q&A Clips That Still Make Sense",
    description: "How to turn interviews into Shorts with clean context, speaker attribution, captions, and a strong answer-driven hook.",
    primaryKeyword: "turn interview into shorts",
    audience: "founders, journalists, recruiters, educators, and content teams",
    searchIntent: "turn an expert or customer interview into short-form clips",
    distinction: "An interview Short succeeds when the viewer understands the question even if the question is mostly removed. The editor has to preserve intent, authority, and consent while making the answer feel fast.",
    bestMoment: "The interviewee answers a question with a specific lesson, objection, confession, before-after result, or memorable phrase.",
    avoid: "Long introductions, name-heavy biography, interviewer interruptions, and clipped answers that sound more certain than the original speaker intended.",
    reviewOwner: "interviewer or subject owner",
    workflow: [
      "Scan the transcript for answer blocks that contain a problem, point of view, and payoff.",
      "Rewrite the missing question into a short on-screen setup only when the answer needs it.",
      "Cut around verbal overlap so the speaker sounds confident but not artificially polished.",
      "Keep speaker names, titles, or company identifiers visible when authority matters.",
      "Review the final caption file for names, numbers, and quoted language before publishing.",
    ],
    signals: [
      "The answer starts after a clear prompt and does not need long interviewer context.",
      "There is a quotable sentence that can become the first caption line.",
      "The clip teaches, proves, or reveals something more specific than the interview topic.",
    ],
    guardrails: [
      "Do not edit out hesitation if the uncertainty is important to the answer.",
      "Avoid stitching two separate answers into one artificial position.",
      "Confirm usage rights when the interview was recorded for a limited purpose.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-podcast-into-shorts", "turn-customer-testimonial-into-shorts", "youtube-shorts-hooks"],
    funnel: "MOFU",
    businessIntent: "interview clip editing",
  },
  {
    source: "Webinar",
    slug: "turn-webinar-into-shorts",
    title: "Turn Webinar into Shorts: Repurpose the Best Teaching Moments",
    description: "A webinar-to-Shorts workflow for slide-heavy recordings, expert demos, Q&A clips, and educational social content.",
    primaryKeyword: "turn webinar into shorts",
    audience: "B2B marketers, educators, agencies, and sales enablement teams",
    searchIntent: "repurpose a webinar replay into short educational clips",
    distinction: "A webinar is usually built for attendance and depth, while a Short is built for one fast insight. The edit has to rescue the useful moment from slides, housekeeping, chat pauses, and long transitions.",
    bestMoment: "The speaker explains one framework, answers a live objection, shows a simple visual, or gives a tactical takeaway from a slide.",
    avoid: "Agenda slides, sponsor intros, broad recaps, and clips where the slide is unreadable on a phone.",
    reviewOwner: "webinar host or demand generation owner",
    workflow: [
      "Mark slide changes and speaker spikes before watching the whole replay in detail.",
      "Choose clips that can stand alone without the registration promise or full deck.",
      "Crop between speaker and slide based on whichever element carries the point.",
      "Replace tiny slide text with short captions or callouts instead of forcing viewers to zoom.",
      "End with the lesson, not with a generic webinar CTA.",
    ],
    signals: [
      "A single slide can be translated into one plain-language takeaway.",
      "The speaker gives an example that makes the abstract concept concrete.",
      "The audience question reveals a pain point future buyers also have.",
    ],
    guardrails: [
      "Do not expose private attendee names, chat messages, or polls without permission.",
      "Avoid using a clip that depends on a downloadable asset the viewer cannot see.",
      "Check brand and legal review when the webinar covers regulated claims.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-online-course-into-shorts", "turn-training-video-into-shorts", "short-form-video-editor-attention-span"],
    funnel: "BOFU",
    businessIntent: "webinar repurposing order",
  },
  {
    source: "Press Conference",
    slug: "turn-press-conference-into-shorts",
    title: "Turn Press Conference into Shorts: Fast Clips With Editorial Context",
    description: "How to turn press conferences into Shorts while preserving attribution, context, captions, and review discipline.",
    primaryKeyword: "turn press conference into shorts",
    audience: "newsrooms, public affairs teams, broadcasters, and agencies",
    searchIntent: "clip official remarks into short-form news updates",
    distinction: "A press conference Short is a public-interest edit. Speed matters, but a misleading crop, missing question, or incomplete sentence can change the meaning of a statement.",
    bestMoment: "A speaker gives a concrete announcement, answers a high-interest question, clarifies a timeline, or corrects a misunderstanding.",
    avoid: "Unattributed fragments, clips that remove the reporter question, and dramatic lines without the policy or event context attached.",
    reviewOwner: "editor or communications lead",
    workflow: [
      "Capture speaker name, role, event name, and timestamp before cutting the clip.",
      "Identify whether the question must stay in the Short for the answer to be accurate.",
      "Use lower thirds and captions to separate speaker claims from newsroom framing.",
      "Keep the cut tight, but do not remove qualifying language that changes meaning.",
      "Route sensitive clips through an editor before publishing to social channels.",
    ],
    signals: [
      "The statement answers what changed, who is affected, or what happens next.",
      "The moment can be verified against the source recording and transcript.",
      "The clip has public value beyond a dramatic sound bite.",
    ],
    guardrails: [
      "Do not use jump cuts that imply a continuous sentence where one did not exist.",
      "Avoid captions that editorialize the speaker's words.",
      "Keep a link or timestamp to the full source recording for internal verification.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-news-broadcast-into-shorts", "turn-parliamentary-session-into-shorts", "ai-video-editing-newsrooms"],
    funnel: "BOFU",
    businessIntent: "newsroom clipping workflow",
  },
  {
    source: "YouTube Video",
    slug: "turn-youtube-video-into-shorts",
    title: "Turn YouTube Video into Shorts: Repurpose Without Duplicating the Whole Video",
    description: "A practical guide to turning existing YouTube videos into Shorts using chapters, comments, captions, and rights-safe edits.",
    primaryKeyword: "turn YouTube video into shorts",
    audience: "YouTubers, channel managers, editors, and creator teams",
    searchIntent: "repurpose a published YouTube video into Shorts",
    distinction: "A YouTube-to-Shorts edit should create a new entry point into the main video. The Short needs its own hook and payoff instead of feeling like a resized trailer.",
    bestMoment: "A tutorial step, opinion, before-after reveal, mistake, result, or audience-favorite segment that can stand alone.",
    avoid: "Random mid-video fragments, reused intros, copyright-unclear footage, and clips that ask viewers to watch the full video before giving value.",
    reviewOwner: "channel owner or editor",
    workflow: [
      "Use chapters, retention notes, comments, and transcript search to find proven interest points.",
      "Choose a segment that delivers value even if the viewer never clicks the long video.",
      "Rewrite the opening line for a vertical viewer who did not see the title or thumbnail.",
      "Crop the frame around face, object, screen, or action rather than preserving the original landscape composition.",
      "Add a related-video or pinned comment strategy after the Short is posted.",
    ],
    signals: [
      "The segment already caused comments, replays, or audience questions.",
      "The moment can be understood without the long video's intro.",
      "The Short gives a complete mini-lesson, reveal, or argument.",
    ],
    guardrails: [
      "Only repurpose videos you own or have permission to use.",
      "Do not hide the source context when the clip includes third-party material.",
      "Avoid turning every chapter into a Short if several chapters target the same query.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-podcast-into-shorts", "turn-live-stream-into-shorts", "youtube-shorts-hooks"],
    funnel: "MOFU",
    businessIntent: "youtube repurposing order",
  },
  {
    source: "Zoom Recording",
    slug: "turn-zoom-recording-into-shorts",
    title: "Turn Zoom Recording into Shorts: Meeting Clips Without the Awkward Parts",
    description: "How to turn Zoom recordings into Shorts from calls, workshops, demos, and remote interviews with clean consent and edits.",
    primaryKeyword: "turn Zoom recording into shorts",
    audience: "remote teams, coaches, consultants, sales teams, and educators",
    searchIntent: "repurpose a Zoom recording into short-form clips",
    distinction: "Zoom recordings usually contain waiting-room chatter, screen shares, gallery view, and uneven audio. The editor has to find the useful moment while protecting participants and private context.",
    bestMoment: "A coach explains a useful idea, a guest answers a question, a presenter shows a result, or a customer reacts to a demo.",
    avoid: "Private participant names, calendar details, messy screen shares, and clips where the speaker is tiny in gallery view.",
    reviewOwner: "meeting host or content owner",
    workflow: [
      "Confirm recording permission, participant consent, and whether the clip is for internal or public use.",
      "Download the highest quality recording and transcript available before editing.",
      "Remove waiting time, tool switching, notification sounds, and side conversations.",
      "Crop to the active speaker or shared screen based on what the viewer needs to understand.",
      "Blur or cut confidential details before adding captions and exporting.",
    ],
    signals: [
      "A remote conversation produces a concise answer or teachable explanation.",
      "The screen share contains a visible before-after or simple demonstration.",
      "The clip is valuable without exposing the meeting's private purpose.",
    ],
    guardrails: [
      "Do not publish internal Zoom recordings without explicit approval.",
      "Avoid showing attendee lists, chat, email, dashboard data, or private documents.",
      "Check Zoom account recording settings and retention rules before sharing source files.",
    ],
    references: ["zoomSupport", "youtubeShorts", "w3cMedia"],
    related: ["turn-google-meet-recording-into-shorts", "turn-microsoft-teams-recording-into-shorts", "turn-internal-meeting-into-shorts"],
    funnel: "BOFU",
    businessIntent: "meeting recording edit",
  },
  {
    source: "Google Meet Recording",
    slug: "turn-google-meet-recording-into-shorts",
    title: "Turn Google Meet Recording into Shorts: Drive Clips With Captions and Context",
    description: "A Google Meet recording workflow for extracting short clips from lessons, team calls, interviews, and demos.",
    primaryKeyword: "turn Google Meet recording into shorts",
    audience: "Google Workspace teams, educators, consultants, and internal comms teams",
    searchIntent: "turn a Google Meet recording into short-form video",
    distinction: "Google Meet recordings often live in Drive with captions, chats, and Calendar context. A good Short uses those assets for accuracy while removing private meeting residue.",
    bestMoment: "A presenter answers a direct question, teaches one point, shows a screen result, or summarizes a decision clearly.",
    avoid: "Drive permission errors, private chat context, tiny shared screens, and moments where the recording starts before the actual topic.",
    reviewOwner: "meeting organizer or Workspace admin owner",
    workflow: [
      "Confirm who can access the Meet recording and whether the clip can leave the organization.",
      "Use the recording, captions, and chat file to verify names, terms, and timestamps.",
      "Cut the recording around one complete explanation rather than the whole agenda item.",
      "Reframe screen shares for phone viewing and replace tiny text with readable captions.",
      "Store the exported Short in the right shared folder so review and permissions stay clear.",
    ],
    signals: [
      "The speaker gives an answer that would help people who missed the meeting.",
      "The recording includes a useful demo or lesson with minimal confidential material.",
      "Captions or chat clarify the terms needed for a clean edit.",
    ],
    guardrails: [
      "Do not assume a Drive recording is approved for public posting.",
      "Remove participant tiles, emails, and private chat where they are not needed.",
      "Follow the organization's Meet recording and consent policy before editing.",
    ],
    references: ["googleMeet", "youtubeShorts", "w3cMedia"],
    related: ["turn-zoom-recording-into-shorts", "turn-microsoft-teams-recording-into-shorts", "turn-internal-meeting-into-shorts"],
    funnel: "BOFU",
    businessIntent: "Google Meet clip editing",
  },
  {
    source: "Microsoft Teams Recording",
    slug: "turn-microsoft-teams-recording-into-shorts",
    title: "Turn Microsoft Teams Recording into Shorts: OneDrive and SharePoint Clip Workflow",
    description: "How to turn Microsoft Teams recordings into Shorts while handling transcripts, permissions, screen shares, and review.",
    primaryKeyword: "turn Microsoft Teams recording into shorts",
    audience: "Microsoft 365 teams, enterprise comms, sales enablement, and training teams",
    searchIntent: "repurpose a Teams meeting recording into short-form clips",
    distinction: "Teams recordings often involve enterprise permissions, transcripts, channel context, and SharePoint or OneDrive storage. The clip workflow has to respect access controls as much as editing craft.",
    bestMoment: "A manager explains a decision, a trainer walks through a step, a customer gives feedback, or a product lead answers a common question.",
    avoid: "Sensitive channel context, unreadable app screens, unapproved participant footage, and clips from meetings with unclear recording permissions.",
    reviewOwner: "meeting organizer, comms owner, or compliance reviewer",
    workflow: [
      "Locate the recording and transcript in the meeting chat, OneDrive, or SharePoint location.",
      "Confirm the meeting policy allows recording, transcription, download, and republishing.",
      "Use the transcript to identify one useful answer, decision, or teachable sequence.",
      "Crop around the active speaker or screen share and remove private collaboration content.",
      "Send the final Short through the same approval path used for internal communications.",
    ],
    signals: [
      "The recording contains a clear decision or reusable explanation.",
      "A screen share shows a process that can be taught in under a minute.",
      "The clip helps employees, prospects, or customers without revealing internal context.",
    ],
    guardrails: [
      "Respect Teams recording permissions and expiry rules.",
      "Do not show whiteboards, notes, or shared apps if they were not captured or approved.",
      "Avoid exporting public clips from internal meetings without legal or comms review.",
    ],
    references: ["microsoftTeams", "youtubeShorts", "w3cMedia"],
    related: ["turn-google-meet-recording-into-shorts", "turn-zoom-recording-into-shorts", "turn-internal-meeting-into-shorts"],
    funnel: "BOFU",
    businessIntent: "Teams recording repurposing",
  },
  {
    source: "Lecture",
    slug: "turn-lecture-into-shorts",
    title: "Turn Lecture into Shorts: Educational Clips Students Actually Finish",
    description: "A focused lecture-to-Shorts workflow for extracting one concept, proof, example, or explanation from long classes.",
    primaryKeyword: "turn lecture into shorts",
    audience: "educators, universities, online teachers, and learning teams",
    searchIntent: "turn a lecture recording into educational Shorts",
    distinction: "A lecture Short is not a compressed class. It should make one concept easier to remember, preview a lesson, or answer a specific learner question.",
    bestMoment: "The instructor defines a concept, solves a small example, corrects a misconception, or explains why a topic matters.",
    avoid: "Full lesson summaries, board text too small to read, and clips where the answer depends on prior classroom context.",
    reviewOwner: "instructor or academic content owner",
    workflow: [
      "Find concept boundaries in the lecture transcript or slides before choosing timestamps.",
      "Select one outcome: define, demonstrate, compare, or correct.",
      "Crop between instructor, board, and slide based on what carries the learning.",
      "Add captions and short labels for formulas, terms, or names that may be hard to hear.",
      "End when the concept lands, not when the lecture segment naturally moves on.",
    ],
    signals: [
      "The clip could answer a search query or student doubt by itself.",
      "A visual example appears in sync with the instructor's explanation.",
      "The idea can be understood without the course syllabus.",
    ],
    guardrails: [
      "Check student privacy before using classroom recordings.",
      "Do not show grades, participant names, or private LMS screens.",
      "Avoid simplifying a concept so much that it becomes inaccurate.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-online-course-into-shorts", "turn-training-video-into-shorts", "turn-webinar-into-shorts"],
    funnel: "MOFU",
    businessIntent: "education clip editing",
  },
  {
    source: "Online Course",
    slug: "turn-online-course-into-shorts",
    title: "Turn Online Course into Shorts: Lesson Clips That Sell the Learning",
    description: "How to turn online course modules into Shorts without giving away the whole course or creating thin teaser clips.",
    primaryKeyword: "turn online course into shorts",
    audience: "course creators, learning businesses, coaches, and educators",
    searchIntent: "repurpose paid or free course videos into short-form clips",
    distinction: "An online course Short should prove teaching quality and create momentum toward the lesson. It should not leak protected course value or become a vague promo.",
    bestMoment: "A mini-framework, common mistake, visual example, or fast before-after lesson from a module.",
    avoid: "Paywalled worksheets, private student examples, vague course trailers, and clips that require the full module to make sense.",
    reviewOwner: "course owner or curriculum lead",
    workflow: [
      "Map the course module to one viewer problem before selecting the clip.",
      "Choose a small lesson that is useful on its own but naturally points to deeper learning.",
      "Remove LMS navigation, private tabs, and long screen setup before cropping.",
      "Add captions that reinforce the teaching steps, not just word-for-word subtitles.",
      "Keep the final CTA educational: next lesson, full course, worksheet, or consultation.",
    ],
    signals: [
      "The clip teaches one thing a non-student can apply today.",
      "The instructor's style and credibility are visible.",
      "The lesson creates curiosity about the broader course without withholding the basic answer.",
    ],
    guardrails: [
      "Do not publish proprietary course material without deciding what belongs in public.",
      "Avoid using student names, assignments, or private cohort conversations.",
      "Make sure claims about outcomes match the full course promise.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-lecture-into-shorts", "turn-webinar-into-shorts", "turn-training-video-into-shorts"],
    funnel: "BOFU",
    businessIntent: "course repurposing order",
  },
  {
    source: "Training Video",
    slug: "turn-training-video-into-shorts",
    title: "Turn Training Video into Shorts: Internal Learning Clips That Stay Accurate",
    description: "A training-video-to-Shorts workflow for turning SOPs, onboarding, product education, and enablement into useful clips.",
    primaryKeyword: "turn training video into shorts",
    audience: "L&D teams, HR, operations, customer success, and sales enablement",
    searchIntent: "turn training recordings into bite-size learning clips",
    distinction: "Training Shorts have to preserve the exact step and policy. They are less about virality and more about recall, compliance, and repeat use.",
    bestMoment: "One process step, safety reminder, product workflow, objection-handling example, or onboarding answer.",
    avoid: "Policy fragments without context, outdated instructions, confidential systems, and clips that skip a required step.",
    reviewOwner: "training owner or operations lead",
    workflow: [
      "Identify whether the clip is for public marketing, customer education, or internal learning.",
      "Cut only one procedure, rule, or skill per Short.",
      "Replace tiny screen elements with readable callouts and captions.",
      "Validate every step with the current SOP or product documentation.",
      "Version the exported clip so old training does not keep circulating after process changes.",
    ],
    signals: [
      "The learner can repeat one action after watching the clip.",
      "The source video shows the actual workflow rather than just talking about it.",
      "The clip reduces a repeated support, onboarding, or manager question.",
    ],
    guardrails: [
      "Do not expose internal dashboards, credentials, or customer data.",
      "Avoid humor or pacing choices that make a compliance topic feel unserious.",
      "Review captions carefully because one wrong word can change a procedure.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-online-course-into-shorts", "turn-lecture-into-shorts", "turn-internal-meeting-into-shorts"],
    funnel: "BOFU",
    businessIntent: "training content repurposing",
  },
  {
    source: "Product Demo",
    slug: "turn-product-demo-into-shorts",
    title: "Turn Product Demo into Shorts: Feature Clips Buyers Can Understand Fast",
    description: "How to turn product demos into Shorts with a clear problem, visible feature, proof moment, and mobile-safe screen crop.",
    primaryKeyword: "turn product demo into shorts",
    audience: "SaaS teams, founders, product marketers, agencies, and sales teams",
    searchIntent: "repurpose a product demo into short-form product clips",
    distinction: "A product demo Short should not show every feature. It should dramatize one pain, one action, and one visible result.",
    bestMoment: "The screen changes from confusing to solved, a feature removes a manual step, or a customer objection gets answered visually.",
    avoid: "Dashboard tours, tiny UI text, feature lists, and clips where the product benefit is only implied.",
    reviewOwner: "product marketer or sales owner",
    workflow: [
      "Name the buyer problem before choosing the demo segment.",
      "Cut everything before the first visible product action unless it sets up the pain.",
      "Zoom, pan, or recreate captions so the important UI detail is readable on mobile.",
      "Use captions to explain the outcome, not every click.",
      "End with a clear proof point: saved step, faster workflow, cleaner handoff, or better result.",
    ],
    signals: [
      "The product value is visible without a long voiceover.",
      "The moment answers a sales question buyers already ask.",
      "The screen state before and after the action is easy to compare.",
    ],
    guardrails: [
      "Do not reveal real customer data or internal environments.",
      "Avoid overstating a feature beyond what the demo shows.",
      "Check UI labels and product names if the interface has changed.",
    ],
    references: ["youtubeShorts", "w3cMedia", "ffmpegDocs"],
    related: ["turn-customer-testimonial-into-shorts", "turn-webinar-into-shorts", "short-form-video-editor-attention-span"],
    funnel: "BOFU",
    businessIntent: "product demo clip order",
  },
  {
    source: "Customer Testimonial",
    slug: "turn-customer-testimonial-into-shorts",
    title: "Turn Customer Testimonial into Shorts: Trust Clips Without Overclaiming",
    description: "A testimonial-to-Shorts workflow for extracting credible customer proof while preserving consent, context, and accuracy.",
    primaryKeyword: "turn customer testimonial into shorts",
    audience: "founders, SaaS marketers, agencies, customer success teams, and sales teams",
    searchIntent: "turn customer testimonial footage into short social proof clips",
    distinction: "A testimonial Short works because it sounds specific and believable. If the edit removes context or pushes the claim too hard, it becomes less trustworthy.",
    bestMoment: "The customer names the problem, explains the decision, shows a result, or describes how work changed after using the product.",
    avoid: "Generic praise, anonymous claims, exaggerated numbers, and edits that hide important limitations.",
    reviewOwner: "customer marketing or account owner",
    workflow: [
      "Confirm testimonial usage rights, customer approval, and any required brand review.",
      "Find the shortest problem-to-result arc in the recording.",
      "Keep the customer's natural language where it signals authenticity.",
      "Add captions for company names, metrics, or terms the viewer must understand.",
      "Let the proof land before adding a light CTA or product context.",
    ],
    signals: [
      "The customer describes a before and after in their own words.",
      "The clip includes a concrete detail rather than a broad compliment.",
      "The speaker's tone feels natural, not coached.",
    ],
    guardrails: [
      "Do not combine separate sentences into a stronger claim than the customer made.",
      "Avoid showing private customer information in screen shares or lower thirds.",
      "Route metrics and regulated claims through legal or customer approval.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-product-demo-into-shorts", "turn-interview-into-shorts", "turn-founder-story-into-shorts"],
    funnel: "BOFU",
    businessIntent: "testimonial video editing",
  },
  {
    source: "Founder Story",
    slug: "turn-founder-story-into-shorts",
    title: "Turn Founder Story into Shorts: Narrative Clips That Build Trust",
    description: "How to turn founder stories into Shorts that reveal the problem, decision, tradeoff, or belief behind a company.",
    primaryKeyword: "turn founder story into shorts",
    audience: "founders, personal brands, startup marketers, and investor-facing teams",
    searchIntent: "repurpose founder story footage into short-form brand clips",
    distinction: "A founder Story Short should not be a miniature biography. It should capture one belief, failure, decision, or turning point that makes the company easier to trust.",
    bestMoment: "The founder explains why the company exists, admits a hard lesson, describes a customer problem, or shares a decision that shaped the product.",
    avoid: "Chronological life stories, vague inspiration, unearned hype, and clips where the founder talks only about themselves.",
    reviewOwner: "founder or brand owner",
    workflow: [
      "Find the tension in the story: what was broken, risky, misunderstood, or hard to change.",
      "Open with the conflict rather than the founder's credentials.",
      "Keep enough personal detail to make the story human, then move quickly to the audience problem.",
      "Use captions to highlight the belief or decision that matters.",
      "End on the lesson, product promise, or reason the company behaves differently.",
    ],
    signals: [
      "The story reveals a specific point of view buyers or users can remember.",
      "The clip has stakes: money, reputation, time, customer pain, or personal risk.",
      "The founder sounds candid rather than rehearsed.",
    ],
    guardrails: [
      "Do not turn the clip into a pitch before the story earns attention.",
      "Avoid claims about competitors or markets that need substantiation.",
      "Cut vanity details if they do not help the viewer understand the company.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-customer-testimonial-into-shorts", "turn-interview-into-shorts", "turn-investor-update-into-shorts"],
    funnel: "MOFU",
    businessIntent: "founder content editing",
  },
  {
    source: "Panel Discussion",
    slug: "turn-panel-discussion-into-shorts",
    title: "Turn Panel Discussion into Shorts: Multi-Speaker Clips With a Clear Point",
    description: "A panel-discussion-to-Shorts workflow for editing disagreement, expert contrast, audience questions, and moderator moments.",
    primaryKeyword: "turn panel discussion into shorts",
    audience: "event teams, publishers, associations, universities, and B2B marketers",
    searchIntent: "turn panel recordings into social clips",
    distinction: "A panel Short has to make multi-speaker context legible quickly. The viewer needs to know who is speaking, why the disagreement matters, and where the takeaway lands.",
    bestMoment: "Two speakers disagree constructively, one expert reframes the topic, or the moderator asks a question the audience cares about.",
    avoid: "Speaker introductions, vague agreement, applause-heavy sections, and edits where names or roles are unclear.",
    reviewOwner: "event editor or content lead",
    workflow: [
      "Build a speaker map with names, titles, and timestamps before cutting.",
      "Choose either one strong answer or one clean contrast between two speakers.",
      "Keep the moderator question if it creates necessary context.",
      "Use lower thirds or captions to identify each speaker on first appearance.",
      "Cut audience reaction only when it supports the meaning of the exchange.",
    ],
    signals: [
      "The exchange contains tension, contrast, or a practical takeaway.",
      "The clip still makes sense if a viewer has never heard of the event.",
      "Speaker identities add credibility instead of clutter.",
    ],
    guardrails: [
      "Do not edit separate speakers into an artificial argument.",
      "Avoid clipping a provocative sentence without the clarifying follow-up.",
      "Confirm event release terms for all panelists.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-conference-talk-into-shorts", "turn-keynote-into-shorts", "turn-event-recording-into-shorts"],
    funnel: "MOFU",
    businessIntent: "event panel repurposing",
  },
  {
    source: "Conference Talk",
    slug: "turn-conference-talk-into-shorts",
    title: "Turn Conference Talk into Shorts: Stage Clips That Keep the Thesis",
    description: "How to turn conference talks into Shorts from key ideas, slide moments, audience reactions, and speaker frameworks.",
    primaryKeyword: "turn conference talk into shorts",
    audience: "conference organizers, speakers, publishers, and B2B teams",
    searchIntent: "repurpose a conference talk into short-form social clips",
    distinction: "A conference talk is designed for a room, but a Short is watched alone on a phone. The edit has to translate stage energy into a self-contained idea.",
    bestMoment: "The speaker states the thesis, shows a surprising slide, tells a short story, or gives a framework the audience can reuse.",
    avoid: "Long stage walks, unreadable slides, applause gaps, sponsor mentions, and setup that only made sense in the room.",
    reviewOwner: "speaker, event marketer, or editorial lead",
    workflow: [
      "Mark thesis moments, audience laughter, slide reveals, and story payoffs.",
      "Choose one idea that represents the talk without pretending to summarize all of it.",
      "Crop around the speaker when emotion matters and around the slide when evidence matters.",
      "Use captions to replace tiny slide text and event-room audio gaps.",
      "Add speaker and event attribution so the clip builds authority.",
    ],
    signals: [
      "The moment would make someone want to hear the full talk.",
      "The speaker's delivery has energy, clarity, or surprise.",
      "The visual or story can be understood without being in the room.",
    ],
    guardrails: [
      "Respect speaker agreements and event media rights.",
      "Do not use audience footage if release terms are unclear.",
      "Avoid turning a nuanced talk into a single misleading hot take.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-keynote-into-shorts", "turn-panel-discussion-into-shorts", "turn-event-recording-into-shorts"],
    funnel: "MOFU",
    businessIntent: "conference clip editing",
  },
  {
    source: "Keynote",
    slug: "turn-keynote-into-shorts",
    title: "Turn Keynote into Shorts: Announcement Clips With a Clear Takeaway",
    description: "A keynote-to-Shorts workflow for extracting announcements, strategic messages, launches, and memorable stage moments.",
    primaryKeyword: "turn keynote into shorts",
    audience: "event teams, executive comms, product marketers, and founder-led companies",
    searchIntent: "turn a keynote recording into short-form clips",
    distinction: "A keynote Short usually carries strategic weight. It should make one announcement, belief, or shift obvious without forcing viewers through the full narrative arc.",
    bestMoment: "The speaker reveals a new product, names a market shift, delivers the central thesis, or tells a story that explains the strategy.",
    avoid: "Ceremonial openings, broad mission language, clips that need the previous slide, and overproduced hype with no concrete point.",
    reviewOwner: "executive comms or product marketing owner",
    workflow: [
      "Separate launch moments, strategic claims, customer proof, and emotional story beats.",
      "Pick one message per Short and write the caption around the audience's takeaway.",
      "Use slide crops only when the slide is legible or can be translated into callouts.",
      "Keep speaker attribution and event branding visible but secondary.",
      "Route announcements through product, legal, or comms review before publishing.",
    ],
    signals: [
      "The clip contains a line people would quote after the event.",
      "A product or strategy shift is visible, not just described.",
      "The edit can stand as an announcement without the whole keynote.",
    ],
    guardrails: [
      "Do not publish unreleased product details ahead of approved timing.",
      "Avoid clipping strategic claims without qualifiers.",
      "Keep the Short aligned with the official launch messaging.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-conference-talk-into-shorts", "turn-founder-story-into-shorts", "turn-product-demo-into-shorts"],
    funnel: "BOFU",
    businessIntent: "keynote repurposing order",
  },
  {
    source: "Earnings Call",
    slug: "turn-earnings-call-into-shorts",
    title: "Turn Earnings Call into Shorts: Investor Clips With Compliance Discipline",
    description: "How to turn earnings calls into Shorts for public markets content without losing context, attribution, or review control.",
    primaryKeyword: "turn earnings call into shorts",
    audience: "IR teams, financial publishers, business media, and executive comms teams",
    searchIntent: "clip earnings call moments into short investor updates",
    distinction: "An earnings-call Short is high-risk content. A clip can move meaning if it drops financial context, forward-looking language, or the source of a statement.",
    bestMoment: "Management explains a business driver, answers an analyst question, clarifies guidance, or comments on a material trend already public.",
    avoid: "Selective metric fragments, hype captions, missing date context, and clips that sound like financial advice.",
    reviewOwner: "investor relations, legal, or financial editor",
    workflow: [
      "Start with the official call transcript, release, and filing context before selecting clips.",
      "Choose a moment that clarifies a public business point, not a line that merely sounds bullish or bearish.",
      "Keep speaker names, role, company, quarter, and date visible in the edit.",
      "Preserve qualifiers around guidance, risks, and forward-looking statements.",
      "Route the export through IR or editorial review before publication.",
    ],
    signals: [
      "The clip answers what changed in the business and why it matters.",
      "The statement can be checked against public materials.",
      "The moment is useful to investors or readers without being promotional.",
    ],
    guardrails: [
      "Do not create a misleading investment signal by removing caveats.",
      "Avoid adding music, graphics, or captions that sensationalize market-sensitive statements.",
      "Keep links to filings, releases, or transcripts in the review notes.",
    ],
    references: ["secEdgar", "youtubeShorts", "w3cMedia"],
    related: ["turn-investor-update-into-shorts", "turn-founder-story-into-shorts", "ai-video-workflow-digital-publishers"],
    funnel: "BOFU",
    businessIntent: "financial media clip workflow",
  },
  {
    source: "Investor Update",
    slug: "turn-investor-update-into-shorts",
    title: "Turn Investor Update into Shorts: Clear Clips for Public or Private Audiences",
    description: "A workflow for turning investor updates into Shorts while separating public messaging, private information, and review steps.",
    primaryKeyword: "turn investor update into shorts",
    audience: "founders, investor relations teams, venture-backed companies, and business media",
    searchIntent: "repurpose investor update video into short clips",
    distinction: "Investor updates can contain sensitive numbers, roadmap details, and claims about traction. The Short should clarify one approved message for the intended audience.",
    bestMoment: "A founder explains a milestone, customer proof, market lesson, product progress, or investor-facing narrative shift.",
    avoid: "Private KPIs, unapproved fundraising claims, confidential customer logos, and clips that make forecasts sound guaranteed.",
    reviewOwner: "founder, IR owner, or legal reviewer",
    workflow: [
      "Decide whether the Short is public social content, investor-only communication, or internal recap.",
      "Mark confidential numbers, names, and roadmap statements before editing.",
      "Pick one approved message and remove side comments that were meant for the room.",
      "Add simple captions for metrics while keeping definitions and time periods clear.",
      "Archive the source timestamp and approval note with the final export.",
    ],
    signals: [
      "The clip explains a milestone in a way a new investor or stakeholder can understand.",
      "The statement is approved for the audience that will see the Short.",
      "The update includes a clear why now, not just a number.",
    ],
    guardrails: [
      "Do not mix public and private investor messaging in the same export path.",
      "Avoid implying guaranteed outcomes from forecasts or goals.",
      "Review customer references, revenue figures, and fundraising language before posting.",
    ],
    references: ["secEdgar", "youtubeShorts", "w3cMedia"],
    related: ["turn-earnings-call-into-shorts", "turn-founder-story-into-shorts", "turn-town-hall-into-shorts"],
    funnel: "BOFU",
    businessIntent: "investor content editing",
  },
  {
    source: "Town Hall",
    slug: "turn-town-hall-into-shorts",
    title: "Turn Town Hall into Shorts: Internal Comms Clips Employees Will Watch",
    description: "How to turn company town halls into Shorts for employee comms while protecting privacy, context, and trust.",
    primaryKeyword: "turn town hall into shorts",
    audience: "internal comms, HR, executive comms, and People teams",
    searchIntent: "repurpose town hall recordings into short internal updates",
    distinction: "A town hall Short is usually for alignment, not public reach. The clip has to preserve trust because employees know the fuller context.",
    bestMoment: "An executive explains a decision, answers a repeated employee question, clarifies priorities, or recognizes a team in a useful way.",
    avoid: "Private Q&A, employee faces without need, strategy details not approved for redistribution, and clips that sound like spin.",
    reviewOwner: "internal comms or People lead",
    workflow: [
      "Define the audience: all-company, department, leadership, or public employer-brand content.",
      "Mark confidential sections, employee names, chat, and unreleased strategy before cutting.",
      "Choose one message that reduces confusion or reinforces a priority.",
      "Keep the leader's wording natural while trimming repetition and meeting setup.",
      "Publish through the internal channel where employees already expect updates.",
    ],
    signals: [
      "The clip answers a question employees are already asking.",
      "The message is clearer as a short video than as a written recap.",
      "The speaker's tone builds confidence instead of corporate distance.",
    ],
    guardrails: [
      "Do not post internal town hall clips publicly unless that use was approved.",
      "Avoid cutting out difficult context to make a decision sound easier than it is.",
      "Blur or remove names, chat, and private documents where needed.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-internal-meeting-into-shorts", "turn-investor-update-into-shorts", "turn-microsoft-teams-recording-into-shorts"],
    funnel: "BOFU",
    businessIntent: "internal communications repurposing",
  },
  {
    source: "Live Stream",
    slug: "turn-live-stream-into-shorts",
    title: "Turn Live Stream into Shorts: Clip the Best Moments After the Broadcast",
    description: "A live-stream-to-Shorts workflow for creators, brands, streamers, and teams repurposing long broadcasts.",
    primaryKeyword: "turn live stream into shorts",
    audience: "streamers, creators, event teams, and brand social teams",
    searchIntent: "turn a live stream recording into short clips",
    distinction: "Live streams have real energy, but they also have dead air, chat pauses, technical checks, and long context. The Short should keep the live feeling while removing the drag.",
    bestMoment: "A reaction, answer, reveal, audience question, mistake recovery, announcement, or demonstration that works without the whole stream.",
    avoid: "Dead air, chat-only context, technical setup, long gameplay or screen time with no explanation, and clips that rely on live audience memory.",
    reviewOwner: "stream owner or social producer",
    workflow: [
      "Use stream markers, chat spikes, comments, or replay timestamps to locate peaks quickly.",
      "Separate reaction clips, teaching clips, announcement clips, and highlight clips.",
      "Cut the lead-in so the viewer reaches the moment within the first seconds.",
      "Keep chat or overlay elements only when they make the moment understandable.",
      "Export platform-specific versions if the same clip goes to Shorts, Reels, TikTok, and LinkedIn.",
    ],
    signals: [
      "Chat activity, replay behavior, or creator reaction points to a clear peak.",
      "The moment has a beginning and payoff despite coming from a long stream.",
      "The clip captures live authenticity without needing the live runtime.",
    ],
    guardrails: [
      "Check music, game, guest, and platform rights before reposting highlights.",
      "Avoid showing private chat, donations, or user data if not intended.",
      "Do not leave in technical artifacts that make the clip feel unfinished.",
    ],
    references: ["youtubeShorts", "w3cMedia", "ffmpegDocs"],
    related: ["turn-youtube-video-into-shorts", "turn-event-recording-into-shorts", "reel-patterns-worth-editing"],
    funnel: "MOFU",
    businessIntent: "live stream clip editing",
  },
  {
    source: "Sports Interview",
    slug: "turn-sports-interview-into-shorts",
    title: "Turn Sports Interview into Shorts: Athlete and Coach Clips With Context",
    description: "How to turn sports interviews into Shorts that capture emotion, analysis, and quotes without losing the game context.",
    primaryKeyword: "turn sports interview into shorts",
    audience: "sports media teams, clubs, leagues, creators, and broadcasters",
    searchIntent: "repurpose sports interviews into short-form clips",
    distinction: "Sports interview Shorts work when the quote is tied to a match, moment, rivalry, comeback, or tactical point. Without context, even a strong quote can feel empty.",
    bestMoment: "An athlete reacts to a decisive play, a coach explains a tactical change, or a player gives a candid answer after pressure.",
    avoid: "Generic post-game cliches, contextless emotion, rights-unclear footage, and clips that misrepresent tone after a loss or controversy.",
    reviewOwner: "sports editor or media rights owner",
    workflow: [
      "Tag the match, date, teams, competition, and speaker before cutting.",
      "Keep the reporter question when it changes the meaning of the answer.",
      "Use score, fixture, or moment context in captions instead of assuming fans know it.",
      "Trim repeated phrases while preserving emotion and sports-specific language.",
      "Check footage, logo, and league rights before combining interview and match visuals.",
    ],
    signals: [
      "The clip explains a key moment fans are already discussing.",
      "The speaker gives emotion or analysis beyond standard media training.",
      "The quote can be understood by a casual fan with one line of context.",
    ],
    guardrails: [
      "Do not strip questions from controversial answers.",
      "Avoid pairing interview audio with unrelated match footage.",
      "Respect league, club, and broadcaster rights around highlights and logos.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-match-highlights-into-shorts", "turn-news-broadcast-into-shorts", "ai-video-workflow-digital-publishers"],
    funnel: "BOFU",
    businessIntent: "sports media repurposing",
  },
  {
    source: "Match Highlights",
    slug: "turn-match-highlights-into-shorts",
    title: "Turn Match Highlights into Shorts: Sports Clips That Tell the Play Clearly",
    description: "A match-highlights-to-Shorts workflow for turning key plays, goals, rallies, and turning points into vertical clips.",
    primaryKeyword: "turn match highlights into shorts",
    audience: "sports publishers, teams, leagues, creators, and broadcasters",
    searchIntent: "repurpose match highlights into short-form sports clips",
    distinction: "A match highlight Short needs sequence, stakes, and rights discipline. The viewer should know what happened, why it mattered, and who owns the footage.",
    bestMoment: "A decisive goal, rally, save, wicket, turnover, finish, record moment, or tactical sequence with a visible payoff.",
    avoid: "Rights-unclear broadcast footage, clips without scoreboard context, overcut sequences, and highlights that start after the setup.",
    reviewOwner: "sports editor or rights manager",
    workflow: [
      "Confirm footage rights and platform permissions before editing.",
      "Start the clip early enough to show the setup, not only the finish.",
      "Use captions for teams, score, minute, period, player, and competition.",
      "Crop the frame so the ball, player, or decisive action stays visible in vertical format.",
      "Keep replay, commentary, and music choices aligned with the license you have.",
    ],
    signals: [
      "The play changes the score, momentum, record, or story of the match.",
      "The viewer can follow the action on a phone without guessing what to watch.",
      "The clip has a clean start, action, and reaction.",
    ],
    guardrails: [
      "Do not use match footage unless you have rights or permission.",
      "Avoid misleading edits that remove fouls, VAR, umpire calls, or sequence context.",
      "Keep scoreboard and player identification accurate.",
    ],
    references: ["youtubeShorts", "w3cMedia", "ffmpegDocs"],
    related: ["turn-sports-interview-into-shorts", "turn-live-stream-into-shorts", "turn-news-broadcast-into-shorts"],
    funnel: "BOFU",
    businessIntent: "sports highlight editing",
  },
  {
    source: "Court Hearing",
    slug: "turn-court-hearing-into-shorts",
    title: "Turn Court Hearing into Shorts: Legal Clips With Context and Restraint",
    description: "How to turn court hearing recordings into Shorts without distorting testimony, rulings, questions, or legal context.",
    primaryKeyword: "turn court hearing into shorts",
    audience: "legal media teams, journalists, civic publishers, and public information teams",
    searchIntent: "turn court hearing footage into short legal clips",
    distinction: "Court hearing Shorts are high-context civic content. Editing must prioritize accuracy, public access rules, and the difference between allegation, argument, evidence, and ruling.",
    bestMoment: "A judge explains a ruling, counsel answers a key question, a procedural point becomes clear, or a public-interest exchange is understandable in context.",
    avoid: "Sensational fragments, testimony without status, private identities, and clips that imply a legal conclusion the court has not reached.",
    reviewOwner: "legal editor or public information reviewer",
    workflow: [
      "Confirm recording access, reuse rights, and any court-specific media restrictions before editing.",
      "Identify speaker role: judge, counsel, witness, defendant, expert, or clerk.",
      "Keep the question or procedural setup when it affects the meaning of the answer.",
      "Use captions to label allegation, argument, evidence, order, or ruling where appropriate.",
      "Send sensitive clips through legal or editorial review before publication.",
    ],
    signals: [
      "The clip clarifies a public-interest legal point rather than just creating drama.",
      "The exchange can be understood without implying guilt, liability, or outcome.",
      "The source timestamp and case context are available for verification.",
    ],
    guardrails: [
      "Do not publish restricted footage or protected identities.",
      "Avoid dramatic music and captions that bias interpretation of legal proceedings.",
      "Do not clip testimony or argument in a way that changes legal meaning.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-parliamentary-session-into-shorts", "turn-press-conference-into-shorts", "turn-news-broadcast-into-shorts"],
    funnel: "BOFU",
    businessIntent: "civic media clip workflow",
  },
  {
    source: "Parliamentary Session",
    slug: "turn-parliamentary-session-into-shorts",
    title: "Turn Parliamentary Session into Shorts: Civic Clips With Speaker Context",
    description: "A parliamentary-session-to-Shorts workflow for turning debates, questions, and committee moments into accurate clips.",
    primaryKeyword: "turn parliamentary session into shorts",
    audience: "newsrooms, civic publishers, broadcasters, advocacy teams, and public affairs groups",
    searchIntent: "repurpose parliamentary footage into short civic clips",
    distinction: "Parliamentary Shorts need speaker identity, chamber context, and procedural clarity. A sharp exchange can be useful, but only if the viewer understands what was being debated.",
    bestMoment: "A member asks a concise question, a minister answers clearly, a committee exchange reveals new information, or a debate line explains the policy stakes.",
    avoid: "Heckling without policy context, party-only framing, incomplete questions, and clips that remove procedural status.",
    reviewOwner: "political editor or public affairs reviewer",
    workflow: [
      "Capture speaker name, role, chamber or committee, date, and debate topic.",
      "Keep the question and answer together when the answer depends on the prompt.",
      "Use neutral captions for policy topic, not partisan interpretation.",
      "Link the clip internally to the full session timestamp for verification.",
      "Review for defamation, election rules, and platform policy where relevant.",
    ],
    signals: [
      "The exchange explains a decision, promise, contradiction, or public-interest point.",
      "The speaker's role matters and can be identified clearly.",
      "The clip adds civic understanding rather than only conflict.",
    ],
    guardrails: [
      "Do not crop out procedural context that changes the exchange.",
      "Avoid captions that turn parliamentary debate into campaign messaging unless that is the approved purpose.",
      "Check official footage terms before publishing on commercial channels.",
    ],
    references: ["parliamentLive", "youtubeShorts", "w3cMedia"],
    related: ["turn-press-conference-into-shorts", "turn-court-hearing-into-shorts", "turn-news-broadcast-into-shorts"],
    funnel: "BOFU",
    businessIntent: "civic video repurposing",
  },
  {
    source: "Documentary",
    slug: "turn-documentary-into-shorts",
    title: "Turn Documentary into Shorts: Story Clips Without Breaking the Narrative",
    description: "How to turn documentary footage into Shorts using character moments, reveal points, tension, and rights-aware edits.",
    primaryKeyword: "turn documentary into shorts",
    audience: "documentary teams, publishers, educators, and cultural organizations",
    searchIntent: "repurpose documentary video into short-form story clips",
    distinction: "A documentary Short should preserve the integrity of the story. It can tease a character, question, or reveal, but it should not strip out context to manufacture a different meaning.",
    bestMoment: "A character faces a turning point, an expert reveals a surprising fact, archival footage changes the story, or a scene captures emotional truth.",
    avoid: "Spoiler-heavy endings, contextless trauma, rights-unclear archival material, and clips that sensationalize a subject.",
    reviewOwner: "director, producer, or editorial lead",
    workflow: [
      "List the documentary's central questions before choosing promotional clips.",
      "Pick scenes that represent the film's tone and ethics, not only the loudest moment.",
      "Use captions to clarify names, places, dates, and archival context.",
      "Protect contributors by checking consent, release forms, and sensitive portrayal notes.",
      "End the Short on curiosity or insight rather than misleading suspense.",
    ],
    signals: [
      "The clip has a character, tension, and meaning in a compact arc.",
      "The viewer learns what the documentary cares about.",
      "The scene is visually strong enough for vertical presentation.",
    ],
    guardrails: [
      "Do not use vulnerable-subject footage as engagement bait.",
      "Avoid remixing archival, music, or third-party material beyond licensed use.",
      "Do not edit a contributor into a position they did not express.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-tv-show-into-shorts", "turn-event-recording-into-shorts", "reel-patterns-worth-editing"],
    funnel: "MOFU",
    businessIntent: "documentary promotion editing",
  },
  {
    source: "TV Show",
    slug: "turn-tv-show-into-shorts",
    title: "Turn TV Show into Shorts: Promo Clips With Rights and Story Control",
    description: "A TV-show-to-Shorts workflow for broadcasters and rights owners turning episodes into short social clips.",
    primaryKeyword: "turn TV show into shorts",
    audience: "broadcasters, studios, streaming teams, fan engagement teams, and publishers",
    searchIntent: "repurpose TV show footage into short social clips",
    distinction: "A TV Show Short is usually promotional and rights-controlled. The edit should invite attention without spoiling the episode or encouraging unauthorized reuse.",
    bestMoment: "A character beat, joke, reveal, cliffhanger setup, expert segment, or scene that communicates the show's tone quickly.",
    avoid: "Major spoilers, unlicensed music segments, full scene dumps, and clips with no episode or show attribution.",
    reviewOwner: "broadcast digital team or rights owner",
    workflow: [
      "Confirm clip length, territory, platform, music, talent, and usage rights.",
      "Choose a scene that sells tone or curiosity without giving away the episode's payoff.",
      "Frame the vertical crop around the character, action, or object that drives the moment.",
      "Use captions and show branding that match the network or platform standards.",
      "Prepare variants for promo, recap, and social conversation if the rights allow it.",
    ],
    signals: [
      "The clip makes the show understandable to someone who has never watched it.",
      "The moment has a visual or emotional hook in the first seconds.",
      "The scene can be promoted without harming the episode experience.",
    ],
    guardrails: [
      "Do not clip TV footage you do not own or have permission to use.",
      "Avoid removing context that changes character meaning or plot stakes.",
      "Check music, talent, and territory restrictions before exporting.",
    ],
    references: ["youtubeShorts", "w3cMedia", "ffmpegDocs"],
    related: ["turn-news-broadcast-into-shorts", "turn-documentary-into-shorts", "ai-video-editing-newsrooms"],
    funnel: "BOFU",
    businessIntent: "broadcast clip workflow",
  },
  {
    source: "News Broadcast",
    slug: "turn-news-broadcast-into-shorts",
    title: "Turn News Broadcast into Shorts: Editorial Clips for Social Platforms",
    description: "How to turn news broadcasts into Shorts with accuracy, lower thirds, captions, editorial review, and newsroom context.",
    primaryKeyword: "turn news broadcast into shorts",
    audience: "newsrooms, broadcasters, publishers, and digital video desks",
    searchIntent: "repurpose news broadcasts into short social clips",
    distinction: "A news broadcast Short has to carry editorial standards into a faster format. The clip should be clear, current, and verifiable without turning the news into a misleading teaser.",
    bestMoment: "An anchor explains the core update, a reporter summarizes verified facts, a correspondent shows a scene, or an interview clarifies what changed.",
    avoid: "Old footage without date context, captions that overstate facts, clips without source attribution, and sensational edits around uncertainty.",
    reviewOwner: "news editor or digital video lead",
    workflow: [
      "Confirm the story status, date, location, and source footage rights before editing.",
      "Cut one update per Short: what happened, what changed, or what viewers need to know.",
      "Keep lower thirds, reporter names, and location labels readable after vertical crop.",
      "Use captions to support verified facts rather than add dramatic framing.",
      "Update or pull clips if the story changes materially after publication.",
    ],
    signals: [
      "The clip answers a timely public question with verified information.",
      "The footage, voiceover, and captions all support the same fact pattern.",
      "The Short points viewers to the broader report without withholding the key update.",
    ],
    guardrails: [
      "Do not reuse archive footage without visible date or context.",
      "Avoid clipping uncertainty as certainty.",
      "Keep editorial sign-off for sensitive civic, health, crime, and conflict stories.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-press-conference-into-shorts", "turn-tv-show-into-shorts", "ai-video-editing-newsrooms"],
    funnel: "BOFU",
    businessIntent: "newsroom video workflow",
  },
  {
    source: "Event Recording",
    slug: "turn-event-recording-into-shorts",
    title: "Turn Event Recording into Shorts: Recaps, Speaker Clips, and Social Proof",
    description: "A workflow for turning event recordings into Shorts from sessions, audience moments, demos, panels, and recaps.",
    primaryKeyword: "turn event recording into shorts",
    audience: "event marketers, agencies, associations, communities, and conference teams",
    searchIntent: "repurpose event footage into short-form clips",
    distinction: "An event recording contains many possible stories: speaker authority, attendee energy, sponsor value, product moments, and community proof. Each Short needs one job.",
    bestMoment: "A speaker lands a key idea, attendees react, a product is demonstrated, or the event atmosphere proves demand.",
    avoid: "Montages with no point, sponsor logos without value, noisy room audio, and clips that rely on being there live.",
    reviewOwner: "event marketer or content producer",
    workflow: [
      "Sort footage into speaker clips, recap clips, testimonial clips, sponsor clips, and atmosphere clips.",
      "Choose the viewer job before editing: educate, sell next year's event, thank attendees, or prove momentum.",
      "Use captions to make stage audio and room noise easier to follow.",
      "Cut around one memorable moment rather than compressing the whole event into one video.",
      "Check attendee releases and sponsor obligations before posting.",
    ],
    signals: [
      "The clip shows why the event mattered, not just that it happened.",
      "A speaker, attendee, or demo gives the Short a clear subject.",
      "The moment would help someone decide to attend, watch, sponsor, or share.",
    ],
    guardrails: [
      "Do not feature attendees prominently without appropriate consent.",
      "Avoid overusing logo walls and generic crowd shots.",
      "Keep sponsor and partner approvals clear when clips include brand obligations.",
    ],
    references: ["youtubeShorts", "w3cMedia"],
    related: ["turn-conference-talk-into-shorts", "turn-panel-discussion-into-shorts", "turn-live-stream-into-shorts"],
    funnel: "MOFU",
    businessIntent: "event repurposing order",
  },
  {
    source: "Internal Meeting",
    slug: "turn-internal-meeting-into-shorts",
    title: "Turn Internal Meeting into Shorts: Private Clips for Alignment and Training",
    description: "How to turn internal meetings into Shorts for employees without exposing confidential context or breaking trust.",
    primaryKeyword: "turn internal meeting into shorts",
    audience: "founders, People teams, internal comms, operations, training, and enablement teams",
    searchIntent: "repurpose internal meeting recordings into short internal clips",
    distinction: "An internal meeting Short is not a public marketing asset. It is a private communication tool for decisions, training, onboarding, and alignment.",
    bestMoment: "A leader clarifies a decision, a teammate explains a process, a customer issue is summarized, or a repeated internal question gets answered.",
    avoid: "Confidential strategy, employee performance details, customer data, private chat, and clips that make a live discussion look like a final policy.",
    reviewOwner: "meeting owner, HR, or internal comms lead",
    workflow: [
      "Decide whether the clip stays internal, goes to a limited team, or can be reused externally.",
      "Mark confidential data, employee names, customer references, and roadmap details before editing.",
      "Choose one durable answer or instruction, not a temporary debate.",
      "Use captions and short labels so employees can scan the clip without sound.",
      "Store the final export in a controlled internal channel with the right permissions.",
    ],
    signals: [
      "The clip reduces repeated questions or onboarding friction.",
      "The speaker gives a clear answer people can act on.",
      "The content remains accurate after the meeting context is removed.",
    ],
    guardrails: [
      "Do not publish internal clips externally without explicit approval.",
      "Avoid sharing private employee, customer, or financial information.",
      "Version and retire clips when policies, tools, or decisions change.",
    ],
    references: ["googleMeet", "microsoftTeams", "zoomSupport", "w3cMedia"],
    related: ["turn-town-hall-into-shorts", "turn-training-video-into-shorts", "turn-zoom-recording-into-shorts"],
    funnel: "BOFU",
    businessIntent: "internal meeting editing",
  },
];

const configBySlug = new Map(sourceToShortsConfigs.map((config) => [config.slug, config]));

export const programmaticShortsPosts = sourceToShortsConfigs.map(buildProgrammaticPost);

export const programmaticShortsInventory = sourceToShortsConfigs.map((config) => ({
  title: config.title,
  slug: `/blog/${config.slug}`,
  cluster: "Source-to-Shorts Conversion",
  pillar: "Turn Long Video into Shorts",
  primaryKeyword: config.primaryKeyword,
  intent: config.searchIntent,
  audience: config.audience,
  funnel: config.funnel,
  contentType: "source-specific workflow guide",
  businessIntent: config.businessIntent,
}));

function buildProgrammaticPost(config) {
  return {
    title: config.title,
    slug: config.slug,
    description: config.description,
    keywords: [
      config.primaryKeyword,
      `${config.source.toLowerCase()} to shorts`,
      `${config.source.toLowerCase()} short video editing`,
      "turn long video into shorts",
    ],
    readingTime: "7 min read",
    date: PUBLISHED_DATE,
    body: buildBody(config),
    heroImage: HERO_IMAGE,
    heroImageAlt: `${config.source} to Shorts editing workflow`,
    imagePrompts: {},
    relatedArticles: config.related.map((slug) => `/blog/${slug}`),
  };
}

function buildBody(config) {
  const sourceLower = config.source.toLowerCase();
  const relatedGuides = config.related.map((slug) => {
    const sourceConfig = configBySlug.get(slug);
    return {
      title: sourceConfig?.title || supportingGuides[slug] || slugToTitle(slug),
      href: `/blog/${slug}`,
    };
  });

  return `![${config.source} to Shorts editing workflow](${HERO_IMAGE})

If you want to turn a ${sourceLower} into a Short, the risky move is treating the source like raw footage and letting a clipper grab whatever sounds punchy. ${config.distinction}

This guide is for ${config.audience}. The goal is a focused, source-specific workflow: one strong vertical Short, clean captions, clear context, and a review path that keeps the final edit honest to the original source.

## Source Brief

| Decision | Best answer for ${config.source} |
| --- | --- |
| Main job | ${config.searchIntent} |
| Best moment | ${config.bestMoment} |
| Avoid | ${config.avoid} |
| Review owner | ${config.reviewOwner} |

## What to Clip First

${config.signals.map((item) => `- ${item}`).join("\n")}

The best ${sourceLower} Short usually starts where the viewer's problem becomes obvious. That may be a question, a visual change, a contradiction, a result, or a speaker saying the thing everyone else avoids saying. Do not start with the source title unless the title itself creates tension.

## Focused Workflow

${config.workflow.map((item) => `- ${item}`).join("\n")}

This is intentionally narrower than a general "make more Shorts" checklist. A ${sourceLower} creates its own editing problems: context, permissions, visual clarity, captions, pacing, and review all change with the source format.

## Editorial Guardrails

${config.guardrails.map((item) => `- ${item}`).join("\n")}

Guardrails matter because short-form editing removes context by design. The fix is not to make the Short longer. The fix is to keep the piece of context that protects the meaning: the question, the speaker role, the date, the source, the screen state, the consent boundary, or the missing visual label.

## How Dalaillama Would Handle This Source

Dalaillama treats a ${sourceLower} as a source format, not just a video file. We look for the moment with the strongest standalone promise, shape the hook, trim the drag, crop for vertical viewing, add readable captions, polish sound, and return a ready-to-post Short. For sensitive sources, the edit should include an approval checkpoint before publishing.

## Credible References

${referencesFor(config).map((ref) => `- [${ref.label}](${ref.url}) ${ref.note}.`).join("\n")}

## Related Guides

${relatedGuides.map((guide) => `- [${guide.title}](${guide.href})`).join("\n")}

### Can Dalaillama turn a ${sourceLower} into Shorts?

Yes. Send the source video or link, tell us the target platform and the content goal, and we can create one focused vertical Short with captions, crop, pacing, and export handled for you.

### How many Shorts should come from one ${sourceLower}?

Start with one or two strong clips. A single clear Short is better than ten weak fragments that target the same idea and compete with each other in search, feeds, and internal reporting.

### What should I send with the recording?

Send the file or link, the target platform, any usage restrictions, the audience, and any timestamps you already know are important. If the source includes private, financial, legal, medical, civic, or internal information, include the review owner before editing starts.`;
}

function referencesFor(config) {
  const keys = Array.from(new Set(config.references));
  return keys.map((key) => referenceLibrary[key]).filter(Boolean);
}

function slugToTitle(slug) {
  return slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
